### ISSUE TITLE
TypeError while operating on bootindexes

### ISSUE THREAD

**Issue by rylanhalteman** [cgevans/scikits-bootstrap#10]
I'm having an issue when calling `ci` with my data.  `t1` & `t2` are python integer arrays with several hundred thousand elements each.  The data range is `0 - ~2000`.

When I call `boot.ci` with my two arrays, I get the following error.

```
    logger.append(boot.ci((t1, t2), multi=True))
  File "/usr/local/lib/python2.7/site-packages/scikits/bootstrap/bootstrap.py", line 166, in ci
    stat = np.array([statfunction(*(x[indexes] for x in tdata)) for indexes in bootindexes])
  File "/usr/local/lib64/python2.7/site-packages/numpy/lib/function_base.py", line 514, in average
    avg = a.mean(axis)
  File "/usr/local/lib64/python2.7/site-packages/numpy/core/_methods.py", line 56, in _mean
    rcount = _count_reduce_items(arr, axis)
  File "/usr/local/lib64/python2.7/site-packages/numpy/core/_methods.py", line 50, in _count_reduce_items
    items *= arr.shape[ax]
TypeError: only integer arrays with one element can be converted to an index
```

Unfortunately I cannot provide any more details at this point, any thoughts?  Could this be an issue with my data?

**Comment by cgevans** [comment]
What are you trying to do? You're passing a tuple of two arrays into boot.ci, but no statfunction argument.  When you pass in a tuple, and have multi=True or multi=None, then boot.ci passes both of those to the statfunction. The default statfunction argument is np.average, which only takes one array. The second array is being interpreted by np.average as the axis to average over, and that's what's causing your error.
