### ISSUE TITLE
negative index

### ISSUE THREAD

**Issue by borgr** [cgevans/scikits-bootstrap#11]
hi, I run the package with all the default parameters and n_samples=100 (actually it does 104, not sure why)
am I using it wrong or what is this exactly?
sometimes it throws that:

/usr/local/lib/python2.7/dist-packages/scikits/bootstrap/bootstrap.py:188: RuntimeWarning: invalid value encountered in divide
  a = np.sum( (jmean - jstat)**3, axis=0 ) / ( 6.0 * np.sum( (jmean - jstat)**2, axis=0)**1.5 )
/usr/lib/python2.7/dist-packages/scipy/stats/_distn_infrastructure.py:1665: RuntimeWarning: invalid value encountered in greater
  cond1 = (scale > 0) & (x > self.a) & (x < self.b)
/usr/lib/python2.7/dist-packages/scipy/stats/_distn_infrastructure.py:1665: RuntimeWarning: invalid value encountered in less
  cond1 = (scale > 0) & (x > self.a) & (x < self.b)
/usr/lib/python2.7/dist-packages/scipy/stats/_distn_infrastructure.py:1666: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0
/usr/local/lib/python2.7/dist-packages/scikits/bootstrap/bootstrap.py:202: InstabilityWarning: Some values used top 10 low/high samples; results may be unstable.
  warnings.warn("Some values used top 10 low/high samples; results may be unstable.", InstabilityWarning)
Traceback (most recent call last):
  File "create_only_real_corrections.py", line 18, in <module>
    m2score_sig(learner_file, gold_file)
  File "/home/borgr/ucca/assess_learner_language/significance_testing.py", line 64, in m2score_sig
    test_significance(statfunction, data, output_dir + str(n_samples)+"_2changes" + filename, n_samples=n_samples)
  File "/home/borgr/ucca/assess_learner_language/significance_testing.py", line 81, in test_significance
    res = scikits.bootstrap.ci(data, statfunction, alpha, n_samples, method, output, epsilon, multi)
  File "/usr/local/lib/python2.7/dist-packages/scikits/bootstrap/bootstrap.py", line 212, in ci
    return stat[(nvals, np.indices(nvals.shape)[1:].squeeze())]
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 100

**Comment by borgr** [comment]
For my understanding it happens when all results are the same, but this was an issue that was supposed to be already solved...

**Comment by cgevans** [comment]
This is fixed, but apparently not in the release.  I'll put out a new release in a few days with some bugfixes.

**Comment by cgevans** [comment]
This should now be fixed in 0.3.3.
