### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by sho-87** [cgevans/scikits-bootstrap#16]
I get an import error when I try to use this package:

`import scikits.bootstrap as bootstrap`

```
Traceback (most recent call last):

  File "<ipython-input-7-6c41ff1e7b16>", line 1, in <module>
    import scikits.bootstrap as bootstrap

  File "C:\Users\Simon\Anaconda3\lib\site-packages\scikits\bootstrap\__init__.py", line 1, in <module>
    from .bootstrap import *

  File "C:\Users\Simon\Anaconda3\lib\site-packages\scikits\bootstrap\bootstrap.py", line 2, in <module>
    from scipy.stats import norm

  File "C:\Users\Simon\Anaconda3\lib\site-packages\scipy\stats\__init__.py", line 348, in <module>
    from .stats import *

  File "C:\Users\Simon\Anaconda3\lib\site-packages\scipy\stats\stats.py", line 175, in <module>
    import scipy.special as special

  File "C:\Users\Simon\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 648, in <module>
    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal

  File "C:\Users\Simon\Anaconda3\lib\site-packages\scipy\special\_ellip_harm.py", line 7, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm

ImportError: cannot import name '_ellipsoid'
```

Im using anaconda 5 with python 3.6. I tried uninstalling/reinstalling both this package and scipy but it doesn't seem to help

**Comment by sho-87** [comment]
seems this is an upstream issue with either anaconda or scipy

**Comment by sho-87** [comment]
after some testing it seems that the problem is specific to `scikits.bootstrap`, or maybe the interaction between this package and anaconda.

Ive posted about this issue over at anaconda as well in case this is something to do with the interaction between them and this package - I'm not sure exactly where the problem is: https://github.com/ContinuumIO/anaconda-issues/issues/6872

with a fresh anaconda 5 install (python 3.6, 64bit, windows 10) I open python and try the following import and everything works fine: `import scipy.stats`

however, when I install this package and try that same import again, I get the error in my original post. I've tried installing using pip, using the whl, and both with and without `--user` and it doesn't fix the problem. the import error still persists

so for some reason, having this package installed prevents certain scipy modules from loading, which is problematic because then `scikits.bootstrap` itself is unusable

**Comment by cgevans** [comment]
This is really bizarre, and per my understanding of Python packaging, shouldn't be possible.  What version of scikits-bootstrap are you using?

**Comment by cgevans** [comment]
Hmmm... looking at the linked bug, I have two comments:

  * Would making the package available via anaconda/conda-forge make sense?
  * I currently have a version of scikits-bootstrap that doesn't actually require scipy (just numpy), and this may become the default at some point.  I'm not sure if this would help.

**Comment by sho-87** [comment]
Im using the latest version 0.3.3. also python 3.6.3 and scipy 0.19.1 (both installed via 64bit anaconda 5 on windows 10)

im not sure if conda forge would fix the problem. maybe? numpy might also fix it, but im not sure what the cause of the problem is

looking through the source here on github doesnt even suggest a scipy dependency...

are you able to replicate the problem when using anaconda?

**Comment by cgevans** [comment]
As this was almost certainly resolved as a consequence of removing scipy entirely, I'm going to close the issue, though feel free to reopen if the problem recurs.
