### ISSUE TITLE
random seed

### ISSUE THREAD

**Issue by shu-hai** [cgevans/scikits-bootstrap#18]
Is there an option to setup a seed for the random number generator in the boostrap function?
I cannot see such an option.

**Comment by cgevans** [comment]
I always just use numpy.random.seed.  See the tests, for example.

**Comment by cgevans** [comment]
In changing to the Numpy Generator API, this is now implemented, with a `seed` argument in the relevant functions, which can take any seed argument that numpy.random.default_rng can take.  This is currently in the numba branch, but I'll try to move it to master soon, and it should be in the next release.
