### ISSUE TITLE
Release version number

### ISSUE THREAD

**Issue by arnau-foraster** [cgevans/scikits-bootstrap#21]
When I try to install scikits-bootstrap to a version that does not exists and be able to see current available version I face the following issue:

pip install scikits-bootstrap==123
Could not find a version that satisfies the requirement scikits-bootstrap==123 (from versions: 1.0.0-pypi2, 0.2, 0.3, 0.3.1, 0.3.2)

Version 1.0.0 has a pypi2 appended,

I think this should be removed and propose a new release with cleaned semantic version.

Regards

**Comment by cgevans** [comment]
It looks like this is now fixed in PyPI, which is the only place it showed up.  Additionally, there is now a new release (1.0.1) with license information, which I think was the original reason for the pypi2 version.
