### ISSUE TITLE
AttributeError: module 'scikits.bootstrap' has no attribute 'pval'

### ISSUE THREAD

**Issue by MatthiVH** [cgevans/scikits-bootstrap#25]
When running the python-file test_boostrap.py, I came accross the following error:

```
.....................E
=====================================================================
ERROR: scikits.bootstrap.test_bootstrap.test_pval.test_pval
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Python 3.5\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\myvhove\Documents\GitHub\scikits-bootstrap\scikits\bootstrap\test_bootstrap.py", line 188, in test_pval
    result = boot.pval(data, np.average, lambda s: 0.98544817 <= s <= 1.06404872, n_samples=NS)
AttributeError: module 'scikits.bootstrap' has no attribute 'pval'
----------------------------------------------------------------------
Ran 22 tests in 4.328s
```
Any idea what the problem might be?
(I'm using python 3.5)(oh and sorry for the bold text, no idea why this happens)

**Comment by cgevans** [comment]
How are you running the tests?  That looks like you are running the tests from the latest git head, but the tests are loading an older version of the module (ie, the latest PyPI version), where pval wasn't present yet.

**Comment by MatthiVH** [comment]
That could be the case. I installed the module using PyPi, but took the script from the github...

**Comment by cgevans** [comment]
Ah: in that case, the tests you're running are trying to test features that aren't in that version.  If you want to run tests on the release version, use the v1.0.1 tag: https://github.com/cgevans/scikits-bootstrap/tree/v1.0.1 .
