### ISSUE TITLE
Numba support

### ISSUE THREAD

**Issue by dbalabka** [cgevans/scikits-bootstrap#28]
Hello! Have you considered improving library performance using the Numba JIT compiler? Any application which has Numba installed can benefit from a performance boost and at the same time we library still backwards compatible with all other applications.

The major advantage of Numba over PyPy is that we do not require to change the interpreter and can still use CPython. In the case of Jupyter we do not require to change the kernel and in the case of any other existing applications, we not forced to migrate to PyPy.

**Comment by cgevans** [comment]
Implemented in 1.1.0
