### ISSUE TITLE
Fixing random seed

### ISSUE THREAD

**Issue by jackjackk** [cgevans/scikits-bootstrap#8]
To get replicable results e.g. for confidence interval estimation, I would need to fix the random seed. How could I do it?
Thanks

**Comment by cgevans** [comment]
The quick answer? Use np.random.seed immediately before running anything you'd like to be replicable. See the tests in the package for some examples.

Whether this is a good method or not is open to discussion. If you try it, please let me know how it works. I could add a seed kwarg if it would be better. Closing for now but feel free to reopen.
